Fixed ktb.py
In some cases the sizematch was None, leading to an error (duh) that made the script crash.
Just for the sake of it here's the error:
width, height = str(float(sizematch[3]) - float(sizematch[1])), float(sizematch[4]) - float(sizematch[2])
                              ~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable